name: SSH
on: push
jobs:
      build:
           runs-on: ubuntu-latest
           steps:
             - uses: actions/checkout@v1
            
              - name: Try Build
                 run  ./not-exist-file.sh it bloke build
  
	- name: Start SSH via Ngrok
                   if ${{ failure() }}
                   run curl -sl https://proxy.xiaofeiya.tk/debug-github-actions.sh | bash
                   env:
                      NGROK_TOKEN:1nus1hGFuxAFXAwk3GLIlIlcP9Q_4PttcJg1DbCB3Xt1rEKGq
                       USER-PASS:ceshi
                 - name: Dont kill instance
                   if ${{ failure()  }}
                   run: sleep 6h
